apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
labels:
  - pairs:
      env: prod
    includeSelectors: true    
namespace: production
resources:
- ../../base
patches:
- path: ./replicas.yaml
- path: ./nodeport.yaml
images:
 - newTag: v1.0
   name: quay.io/redhattraining/hello-world-nginx
